# Generated by Django 5.2 on 2025-04-20 08:06

import django.db.models.deletion
import events.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('nom', models.CharField(blank=True, max_length=240, null=True)),
                ('prix', models.CharField(blank=True, max_length=240, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('lieu', models.CharField(max_length=240)),
                ('chronogramme', models.FileField(null=True, upload_to='documents/')),
                ('image', models.ImageField(upload_to='EventImage/')),
                ('slogan', models.CharField(max_length=240, null=True)),
                ('lien_diffusion', models.CharField(max_length=240, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', validators=[events.models.validate_video_file])),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('createur', models.ForeignKey(blank=True, limit_choices_to={'profile_type': 'creator'}, on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_ticket', to='events.typeticket')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('evenement', models.ManyToManyField(to='events.evenement')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField()),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Validée', 'Validée'), ('Annulée', 'Annulée')], default='En attente', max_length=20)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='events.evenement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Intervenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=240)),
                ('fonction', models.CharField(max_length=240, null=True)),
                ('description_fonction', models.TextField(null=True)),
                ('photo_profil', models.ImageField(null=True, upload_to='IntervenantImage/')),
                ('evenement', models.ManyToManyField(to='events.evenement')),
            ],
        ),
        migrations.CreateModel(
            name='LienReseauSociaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(blank=True, max_length=240, null=True)),
                ('facebook', models.CharField(blank=True, max_length=240, null=True)),
                ('twitter', models.CharField(blank=True, max_length=240, null=True)),
                ('linkedIn', models.CharField(blank=True, max_length=240, null=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Lien_Reseaux', to='events.intervenant')),
            ],
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('evaluation', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Avis', to=settings.AUTH_USER_MODEL)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Avis', to='events.evenement')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('evaluation__gte', 1), ('evaluation__lte', 5)), name='avis_evaluation_between_1_and_5')],
            },
        ),
    ]
