# Generated by Django 5.2 on 2025-04-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Événement public'),
        ),
    ]
