# Generated by Django 5.2 on 2025-04-26 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_evenement_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='is_public',
        ),
    ]
